name: Deploy V3 Site

on:
  push:
    branches: [3.x]
    paths:
      - 'packages/vant/docs/**'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          ref: '3.x'

      - name: Install pnpm
        run: npm i pnpm@7 -g

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Site
        run: npm run build:site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: packages/vant/site-dist
          clean: false

      - name: Deploy for GitHub 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: main
          folder: packages/vant/site-dist
          token: ${{ secrets.VANT_UI_TOKEN }}
          repository-name: vant-ui/vant-ui.github.io
          target-folder: vant
          clean: false
